### PR TITLE
Spiced up the README

### PR DESCRIPTION
**Pull request by AdvaitDhingra**

### CODE REVIEW

**Comment by keithvetter** [comment]
Advait, thanks for the README updates.  I need to get to the merge requests, but have other repos that I'm pushing to and need to figure out the best workflow for that.

**Comment by AdvaitDhingra** [comment]
> Advait, thanks for the README updates. I need to get to the merge requests, but have other repos that I'm pushing to and need to figure out the best workflow for that.

No probem. Take your time

**Comment by AdvaitDhingra** [comment]
Hey, @keithvetter , happy easter. Hope you're doing well. Would you like to review this pr now?

**Comment by keithvetter** [comment]
Hey Advait, we recently added GitHub Actions, and that pull request modded the Readme, so just going with that version.  The changes have CI for Ubuntu, so hopefully you'll be good now.

**Comment by AdvaitDhingra** [comment]
> Hey Advait, we recently added GitHub Actions, and that pull request modded the Readme, so just going with that version. The changes have CI for Ubuntu, so hopefully you'll be good now.

Ah ok.

**Pull request closed without merging**
